"""initial

Revision ID: 132a2df0c403
Revises: 
Create Date: 2023-07-17 17:21:31.289577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132a2df0c403'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasklist_id'), 'tasklist', ['id'], unique=False)
    op.create_index(op.f('ix_tasklist_user_id'), 'tasklist', ['user_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['tasklist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_tasklist_user_id'), table_name='tasklist')
    op.drop_index(op.f('ix_tasklist_id'), table_name='tasklist')
    op.drop_table('tasklist')
    # ### end Alembic commands ###
